settings:
  allowed-regex: "^[а-яА-ЯёЁa-zA-Z]+$"
  todo-separator: "*"
  local-chat:
    radius: 100.0
  roll:
    default-min: 0
    default-max: 100

formats:
  me: "{colored_name} &7{text}"
  do: "&7{text} &e({colored_name}&e)"
  try: "{colored_name} &7{text} &8| {result}"
  roll: "{colored_name} &7кинул кубик &8(&7{min}-{max}&8). &7Результат: &a{result}"
  todo: "{colored_name} &7{action}, сказал: &f{speech}"
  try-success: "&aУдачно"
  try-fail: "&cНеудачно"
